name: Challenge 3 - Node.js CI

on:
  push:
    paths:
    - 'apis/userprofile_broken/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --prefix apis/userprofile install
    - run: npm --prefix apis/userprofile run build --if-present
    - run: npm --prefix apis/userprofile test
      env:
        CI: true
    - name: create issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
